### ISSUE TITLE
Create braille printer file

### ISSUE THREAD

**Issue by faizan170** [AaditT/braille#2]
Hi, How we can save braille text in a file so that a braille printer can print that. Like for a string, we can create braille charcters, but what file format we can use or how can we write them in a file.
Thanks.

**Comment by AaditT** [comment]
Hi, it really depends on the printing mechanism you are looking for. There have been open source 3d printing projects which use custom 3d modeling software to develop the prints. Braille embossers are another way to print out braille, and these embossers rely on braille translation software.
